### ISSUE TITLE
开发建议

### ISSUE THREAD

**Issue by gclm** [clouDr-f2e/rubick#10]
## 1、期待跨平台的解决方案。
目前我也有和作者类似的遭遇，个人开发的公司相关插件不能发布到utool。导致更新特别麻烦

## 2、希望个人本地数据可以自定义同步到git仓库，就像idea的配置仓库同步一样

**Comment by muwoo** [comment]
@gclm 个人本地数据自定义同步到git仓库，您是想解决配置多人共享以及远端配置共享的目的是吧？这快就得划好界限了，得区分个性数据和共性数据。这块可以考虑考虑，我先加到todolist 里面，但是实现方式可能不像idea，因为 Rubick 不仅仅给开发用，其他同学没有git仓库，不会clone，只能下载加载

**Comment by gclm** [comment]
我主要是想解决不同端配置共享问题，另外对于个性数据和共性数据的判断可以交给用户，让他们选择，只要使用这个同步功能，就需要选择什么同步什么不同步。

**Comment by muwoo** [comment]
@gclm em... 明白你的意思，但这种场景应该不多吧，不同端的配置共享我理解只用放到 server 端存一下就好了。这块我会考虑支持的
