### ISSUE TITLE
Esc退出/隐藏  模糊拼音搜索

### ISSUE THREAD

**Issue by Tim-Paik** [clouDr-f2e/rubick#16]
**您的功能请求是否与问题相关？ 请简单描述.**
1. 想要在按ESC键时隐藏
2. 希望能支持utools的模糊/拼音搜索

Windows 11 x64

**请描述一下您想要的解决方案**
按ESC时能隐藏窗口
输入 `截图`/`jieping`/`jp` 时能打开截屏功能，我认为这是utools最杀手级的功能之一了

**描述你考虑过的替代方案**
目前没有

**Comment by muwoo** [comment]
@Tim-Paik 
MacOS 已支持：https://github.com/clouDr-f2e/rubick/commit/a35a5ccfc38bea8c6d1ac5a1c00eb02573fea7d9
Windows 开发中
