### ISSUE TITLE
建议禁止程序重复运行

### ISSUE THREAD

**Issue by kyseven** [clouDr-f2e/rubick#17]
建议禁止程序重复运行

**Comment by muwoo** [comment]
@kyseven 可以再具体描述一下您遇到的问题吗？

**Comment by XingXiaoWu** [comment]
启动加个锁就行了，就不会启动两个实例

**Comment by Gu-Miao** [comment]
https://www.electronjs.org/docs/api/app#apprequestsingleinstancelock

**Comment by muwoo** [comment]
@kyseven 已修复，感谢支持 [release](https://github.com/clouDr-f2e/rubick/releases/tag/v0.0.3-beta.2)
