### ISSUE TITLE
超级面板有 utools 图标

### ISSUE THREAD

**Issue by ayuayue** [clouDr-f2e/rubick#19]
跟 utools 的超级面板页面显示相同,因为 utools 不开源,所以担心会有版权等问题,请注意.
还有就是如果也可以  esc 键关闭打开的插件及关闭窗口就好了,
插件中心的生态还需丰富
很棒的应用

**Comment by muwoo** [comment]
@ayuayue 感谢提醒，已删除，ESC已支持，shift+ESC.
