### ISSUE TITLE
无法禁止开机自动启动

### ISSUE THREAD

**Issue by hjonline** [clouDr-f2e/rubick#22]
**描述一下这个bug**
在设置界面选择了取消开机自动启动后，仍然保留了开机自动启动，就是说选择没有生效。

**复现方式**
1. Go to '偏好设置'
2. Click on '设置'
3. Click on '开机启动'
4. 开关滑动，变灰，但是用 autoruns 一看，还是自动启动，重启电脑，还是自动启动。

**Comment by muwoo** [comment]
@hjonline 已修复 感谢支持
