### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Mike-hd123** [clouDr-f2e/rubick#27]
## 任何开发建议、交流学习都可以
希望添加关闭托盘图标。

**Comment by muwoo** [comment]
@Mike-hd123 最新的包已经支持。

**Comment by Mike-hd123** [comment]
移动窗口支持了，但是没有看到关闭托盘图标。是要自己编译一个最新包吗？

**Comment by muwoo** [comment]
@Mike-hd123 macos 还是windows？现在应该都不会出现任务栏托盘了。
macos 只有右上角的任务栏图标：
![image](https://user-images.githubusercontent.com/21073039/129652422-ff032ea7-9943-4204-9f6d-e57d51acadc2.png)

**Comment by Mike-hd123** [comment]
windows最新测试版。
![image](https://user-images.githubusercontent.com/50143395/129652600-53db7c5b-10d8-43c7-93d0-000353b3c248.png)
我重新下载试试。
![image](https://user-images.githubusercontent.com/50143395/129652661-3f72203a-49b2-4347-8259-ce681f65bb8c.png)
一样，设置里面也没有关闭托盘图标。

**Comment by muwoo** [comment]
@Mike-hd123 哦哦，这个任务小图标需要关闭吗？关闭不就是`退出` 功能么~

**Comment by Mike-hd123** [comment]
不是，是后台运行着，但是不显示托盘图标。弄个可选功能，挺好的。utools官方很久就说不做了，怕奔溃，然后其他人有不会用任务管理器关闭重启。就留着。。。

**Comment by Mike-hd123** [comment]
https://yuanliao.info/d/1502-utools/3
这是链接。

**Comment by muwoo** [comment]
@Mike-hd123 我了解了解

**Comment by muwoo** [comment]
@Mike-hd123 感觉这个功能有点鸡肋，先不考虑了，后面再看吧
