### ISSUE TITLE
osx-mouse不支持Linux系统

### ISSUE THREAD

**Issue by SOVLOOKUP** [clouDr-f2e/rubick#3]
跨平台是一个很重要的属性，osx-mouse可以用iohook代替

另外我希望能深度参与该项目的开发与维护，如何联系?

**Comment by muwoo** [comment]
@SOVLOOKUP 您好，由于本人精力有限，目前改桌面端工具只支持 macos 后续等成熟稳定再考虑支持其他系统。也非常欢迎您能投入开发与维护，具体的事项您可以把你的微信号通过邮件的方式发送给我 2424880409@qq.com
