### ISSUE TITLE
显示窗口后 CPU 占用飙升，卡顿

### ISSUE THREAD

**Issue by pluveto** [clouDr-f2e/rubick#31]
**描述一下这个bug**
![image](https://user-images.githubusercontent.com/50045289/130732301-8738f210-afa5-4b13-93ff-2b587f08d459.png)

**复现方式**
安装，运行，按 alt+R

怀疑是有死循环？

**Comment by pluveto** [comment]
另外四个选项卡切换耗时要四五秒。窗口拖动会冻结鼠标。

**Comment by muwoo** [comment]
@pluveto 已修复，为了你这个bug，我专门花重金买了个 Paralles Desktop 心疼ing，bug主要原因是用了electron 的 touchBar 但是没有判断 win 环境，不知道为啥在win环境会卡死。现在加了层判断
