### ISSUE TITLE
Windows端粘贴板是json文件时无法触发onSearch

### ISSUE THREAD

**Issue by xingjizhilv** [clouDr-f2e/rubick#32]
**描述一下这个bug**
Windows端复制json文件无法安装插件

**复现方式**
1.Ctrl+C 复制文件
2.在rubick中Ctrl+V无反应
3.通过Debug发现在输入框Ctrl+V时没进onSearch

**预期行为**
这属于平台差异问题，Windos端的很多功能都没法正常使用

**Comment by muwoo** [comment]
@xingjizhilv 已修复，为了你这个bug，我专门花重金买了个 Paralles Desktop 心疼ing

**Comment by xingjizhilv** [comment]
好滴 幸苦你啦 待会给您捐助十块钱



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月31日(周二) 晚上9:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [clouDr-f2e/rubick]Windows端粘贴板是json文件时无法触发onSearch (#32)




 
@xingjizhilv 已修复，为了你这个bug，我专门花重金买了个 Paralles Desktop 心疼ing
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by muwoo** [comment]
@xingjizhilv 😘😘😘

**Comment by muwoo** [comment]
@xingjizhilv 安装包 >= 0.0.3-beta.8
