### ISSUE TITLE
windows最新版本启动报错

### ISSUE THREAD

**Issue by fuxingjun** [clouDr-f2e/rubick#44]
**描述一下这个bug**
这就不用描述了吧

**复现方式**
windows启动

**截图**
![image](https://user-images.githubusercontent.com/25798786/132273870-79fe85dd-8c4a-4a80-8da6-bd15df6caea1.png)
![image](https://user-images.githubusercontent.com/25798786/132273891-488535f8-89de-4c94-87ac-7c23333b6064.png)

**Comment by muwoo** [comment]
@fuxingjun windows  下要获取exe文件的icon图标，用了一个库[IconExtractor](https://github.com/ScienceVikings/IconExtractor)，这个库目前发现在electron build 后会报错：https://stackoverflow.com/questions/60908883/error-write-epipe-occurring-only-when-electron-application-is-built 哎，正在寻找替代方案

**Comment by muwoo** [comment]
@fuxingjun 已修复，但是现在取icon还是有问题，目前系统应用展示不出来icon，这块待优化
