### ISSUE TITLE
mac 端使用快捷键显示进程异常

### ISSUE THREAD

**Issue by gclm** [clouDr-f2e/rubick#48]
**描述一下这个bug**
mac 端使用快捷键显示窗口异常
![image](https://user-images.githubusercontent.com/27618687/134460332-ca76d61e-f798-46d4-b82f-8d4605c0bea5.png)

**复现方式**
1. 安装应用
2. 使用快捷键打开软件

**预期行为**
正常显示窗口

**Comment by muwoo** [comment]
@gclm 那个版本的rubick

**Comment by gclm** [comment]
- rubick : 0.0.7-beta.2
- mac： 11.6

**Comment by muwoo** [comment]
@gclm 已修复：https://github.com/clouDr-f2e/rubick/commit/50452bc36bb1aa704610294fb309310afafac54d#diff-f4eb0b10c84510212b6b5d4268241a83b9583e6c5fdb1357fafc041503f55babL109
