### ISSUE TITLE
 Windows下无法使用Alt+Space为快捷键

### ISSUE THREAD

**Issue by someone120** [clouDr-f2e/rubick#52]
**描述一下这个bug**
Windows下无法使用Alt+Space为快捷键

**复现方式**
嘛就是设置快捷键

**预期行为**
快捷键变成Alt+Space

**截图**
![image](https://user-images.githubusercontent.com/47704813/134805935-695fb2f6-639c-4f0e-8804-aebebe99a0b3.png)

好像是因为和windows的快捷键冲突了才没法设置

**Comment by muwoo** [comment]
@someone120 刚才试了一下，确实是因为windows `alt + space` 先弹出了系统菜单，冲突了这里的设置

**Comment by muwoo** [comment]
已修复

**Comment by orangex** [comment]
@muwoo win11，与楼主一模一样，现在仍然无法shezhi alt+space
